spring.application.name=bookNstay


#DB Configurations
spring.datasource.url=jdbc:postgresql://${DB_HOST_URL}:5432/${DB_NAME}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api/v1

#To get Json response in same order as we create the DTO
spring.jackson.mapper.sort-properties-alphabetically=false

#SecretKey
jwt.secretKey=${JWT_SECRET_KEY}

#frontend url
frontend.url=http://localhost:8080

#Stripe SecretKey
stripe.secret.key=${STRIPE_SECRET_KEY}

#Webhook secret generated via CLI
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
