spring.application.name=bookNstay


#DB Configurations
spring.datasource.url=jdbc:postgresql://${DB_HOST_URL}:5432/${DB_NAME}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
#postgres - Yashwanth@123

server.servlet.context-path=/api/v1


#To get Json response in same order as we create the DTO
spring.jackson.mapper.sort-properties-alphabetically=false


#SecretKey
jwt.secretKey=${JWT_SECRET_KEY}
#jehfwbjqh3bh24394092dfqeahbacndjefvbjhvcyctrxerew3a224